language: ruby
rvm:
  - 2.6.3

notifications:
  email: false

branches:
  except:
    - production

addons:
  postgresql: "11.5"

bundler_args: --without development --deployment --jobs=3 --retry=3

cache: bundler

before_script:
  - sudo service postgresql stop
  - sudo service postgresql start
  - psql -c 'create database ekt_library_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
#  - cp config/secrets.travis.yml config/secrets.yml
  - bundle exec rake db:setup
  - 'bundle exec rackup -s puma -E production private_pub.ru &'
  - sleep 3

gemfile:
  - Gemfile